package com.yourname.premiumah.listener;

import com.yourname.premiumah.gui.GuiManager;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;

public final class PlayerSessionListener implements Listener {
    private final GuiManager guiManager;

    public PlayerSessionListener(GuiManager guiManager) {
        this.guiManager = guiManager;
    }

    @EventHandler
    public void onQuit(PlayerQuitEvent event) {
        guiManager.handleQuit(event.getPlayer());
    }
}
